#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#
x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped

services:
  firefly:
    container_name: firefly
    image: fireflyiii/core:latest
    <<: *basics

    environment:
      - APP_KEY=${FIREFLY_APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=${MARIA_DB_HOST:-maria-db}
      - DB_PORT=${MARIA_DB_PORT:-3306}
      - DB_DATABASE=${FIREFLY_DB_NAME}
      - DB_USERNAME=${FIREFLY_DB_USER}
      - DB_PASSWORD=${FIREFLY_PASSWORD}
      - APP_URL=https://${FIREFLY_SUBDOMAIN}.${ROOT_DOMAIN}
      - TRUSTED_PROXIES=**
      - TZ=${TZ}

    volumes:
      - ~/volumes/firefly/upload:/var/www/html/storage/upload
      - ~/volumes/firefly/db:/var/lib/mysql
    ports:
      - "${FIREFLY_PORT:-8080}:8080"
    networks:
      core:
        ipv4_address: 172.20.0.50
      internal:


    depends_on:
      maria-db:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`${FIREFLY_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"

  firefly-importer:
    container_name: firefly-import
    image: fireflyiii/data-importer:latest
    <<: *basics

    environment:
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://${FIREFLY_SUBDOMAIN}.${ROOT_DOMAIN}
      - TZ=${TZ}

    networks:
      core:
        ipv4_address: 172.20.0.51
      internal:


    depends_on:
      firefly:
        condition: service_healthy
    ports:
      - "${FIREFLY_IMPORTER_PORT:-8081}:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${FIREFLY_IMPORTER_PORT}/health" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-import.rule=Host(`${FIREFLY_SUBDOMAIN}-import.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.firefly-import.entrypoints=websecure"
      - "traefik.http.routers.firefly-import.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly-import.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly-import.loadbalancer.server.port=${FIREFLY_IMPORTER_PORT:-8081}"

  firefly-cron:
    image: alpine:latest
    container_name: firefly-cron
    <<: *basics

    environment:
      - TZ=${TZ}

    command: >
      sh -c "
        apk add --no-cache tzdata curl
        && ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime
        && echo \"0 3 * * * curl -sS http://firefly:${FIREFLY_PORT}/api/v1/cron/${FIREFLY_CRON_TOKEN}\" | crontab -
        && crond -f -L /dev/stdout
      "

    networks:
      core:
        ipv4_address: 172.20.0.52
      internal:


    depends_on:
      firefly:
        condition: service_healthy

volumes:
  firefly_iii_upload:
  firefly_iii_db:
