#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#
x-basics: &basics
  env_file:
    - .env
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: ${FIREFLY_III_SUBDOMAIN}
    <<: *basics
    networks:
      core:
        ipv4_address: 172.20.0.50
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    ports:
      - '8010:8080'
    environment:
      - DB_HOST=maria-db
      - DB_PASSWORD=${FIREFLY_III_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly.loadbalancer.server.port=8010"

  firefly-importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly-import
    networks:
      core:
        ipv4_address: 172.20.0.51
    ports:
      - '8110:8080'
    depends_on:
      - firefly
    environment:
      - FIREFLY_III_URL=http://${FIREFLY_III_SUBDOMAIN}
      - VANITY_URL=https://${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-import.rule=Host(`firefly-import.zephyrex.dev`)"
      - "traefik.http.routers.firefly-import.entrypoints=websecure"
      - "traefik.http.routers.firefly-import.middlewares=dashboard-auth,cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly-import.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly-import.loadbalancer.server.port=8080"

  firefly-cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly-cron
    restart: always
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN};echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      core:
        ipv4_address: 172.20.0.52
volumes:
   firefly_iii_upload:
   firefly_iii_db:
