#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#
x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped

services:
  firefly:
    image: fireflyiii/core:latest
    <<: *basics

    environment:
      - APP_KEY=${FIREFLY_III_APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=maria-db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=${FIREFLY_III_PASSWORD}
      - APP_URL=https://${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}
      - TRUSTED_PROXIES=**
      - TZ=${TZ}

    volumes:
      - ~/volumes/firefly/upload:/var/www/html/storage/upload
      - ~/volumes/firefly/db:/var/lib/mysql

    networks:
      core:
        ipv4_address: 172.20.0.50
      internal:

    depends_on:
      maria-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"

  firefly-importer:
    image: fireflyiii/data-importer:latest
    <<: *basics

    environment:
      - FIREFLY_III_URL=http://firefly:8080
      - VANITY_URL=https://${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}
      - TZ=${TZ}

    networks:
      core:
        ipv4_address: 172.20.0.51
      internal:

    depends_on:
      firefly:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-import.rule=Host(`import.${FIREFLY_III_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.firefly-import.entrypoints=websecure"
      - "traefik.http.routers.firefly-import.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.firefly-import.tls.certresolver=cloudflare"
      - "traefik.http.services.firefly-import.loadbalancer.server.port=8080"

  firefly-cron:
    image: alpine:latest
    container_name: firefly-cron
    <<: *basics

    environment:
      - TZ=${TZ}

    command: >
      sh -c "
        apk add --no-cache tzdata curl
        && ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime
        && echo \"0 3 * * * curl -sS http://firefly:8080/api/v1/cron/${FIREFLY_III_CRON_TOKEN}\" | crontab -
        && crond -f -L /dev/stdout
      "

    networks:
      core:
        ipv4_address: 172.20.0.52
      internal:

    depends_on:
      firefly:
        condition: service_healthy

volumes:
  firefly_iii_upload:
  firefly_iii_db:
